print('Input')
nama = input('Nama                      : ')
nim = input('NIM                       : ')
kelas_paralel = input('Kelas Paralel             : ')
ttl = input('Tempat/Tanggal Lahir      : ')
alamat = input('Alamat                    : ')
hobby = input('Hobby                     : ')
no_hp = input('No. Hp                    : ')

print('\nOutput')
print('Nama                      : ', nama)
print('NIM                       : ', nim)
print('Kelas Paralel             : ', kelas_paralel)
print('Tempat/Tanggal Lahir      : ', ttl)
print('Alamat                    : ', alamat)
print('Hobby                     : ', hobby)
print('No. Hp                    : ', no_hp)
